### ISSUE TITLE
Investigate human verification pipelines

### ISSUE THREAD

**Issue by typicalTYLER** [typicalTYLER/SolarPanelDataWrangler#3]
Could be as simple as sending out an excel sheet of locations, or as complicated as rolling our own verification software.

Some existing solutions:
[MapRoulette](https://maproulette.org/)
[OpenGridMap](http://opengridmap.com/)

**Comment by typicalTYLER** [comment]
MapRoulette looks pretty promising, once we have some data we can put it in this challenge that I made and see how well it works https://maproulette.org/admin/project/3749/challenge/3953

**Comment by sallamander** [comment]
I agree, MapRoulette looks really promising, and from a cursory look at the [GH repository](https://github.com/osmlab/maproulette3) it looks like we should be able to set up a programatic pipeline to feed the results of your [run_inference](https://github.com/typicalTYLER/SolarPanelDataWrangler/blob/master/run_inference.py) script right into a challenge that people could then work through.

**Comment by typicalTYLER** [comment]
Agreed! I think the act of creating ways and tagging everything correctly might be a little more difficult than most MapRoulette tasks, but hopefully if we tag it as expert we can get people to work on it!

Another avenue we might explore, if this is too complicated a task for MapRoulette, is this import pipeline: https://wiki.openstreetmap.org/wiki/Austin,_TX/Buildings_Import#The_Plan I was doing some research to see why some Austin data seemed misaligned, and this was the import method they used for building alignments. But it seems a little more involved.

**Comment by sallamander** [comment]
That import pipeline definitely seems more involved that using MapRoulette, so it's probably worth giving MapRoulette a shot first unless we were pretty convinced it wouldn't work. I'm actually not 100% clear on what we need to do on MapRoulette, do we have that documented somewhere that I could use to get up to speed? I guess I had just been imagining using it as human verification, but that sounds incorrect. Are we also hoping that they'll provide finer details on *where* the solar panels are in each image? 

Regardless, I'm wondering if it might be possible to break up each MapRoulette task into smaller subtasks and then chain the subtasks to get the final result. That might help make it easier / more digestible for people working on it.

**Comment by sallamander** [comment]
@typicalTYLER do you have plans to start building a pipeline for taking results from the `run_inference` script and porting them into a MapRoulette job?

**Comment by typicalTYLER** [comment]
I'm currently working on a script to output positive results into a MapRoulette task (shouldn't be too much work), I can go ahead and assign myself this issue to represent that. There's not much documentation/discussion so far other than what I've written on the [Solar PV Mapping Project document](https://docs.google.com/document/d/1EFbziZ5OMzyVnIgw-x4AX2GZg91L-BrbbX2u1a7xx1Q) at the very bottom. I was basically imagining each task being a bounding box representing the tile above a certain softmax threshold, and asking the human to create a bounding box around at least all the solar arrays within the tile. (Or skipping if it was a false positive, etc.)

**Comment by typicalTYLER** [comment]
Added some functionality to create a geojson file for individual tasks as described above here: 961701820826dd0db2e8bd2f57f640876bf53c3c, having trouble uploading 5601 tasks to MapRoulette though. It's stuck at 400. So I've created an issue here: https://github.com/osmlab/maproulette3/issues/701

**Comment by typicalTYLER** [comment]
I've added more features to increase the quality of the generated MapRoulette challenge (filtering, clustering), here's a challenge for Austin, Texas: https://maproulette.org/browse/challenges/4013

Short of rolling our own verification software, this seems to work pretty well. We just need more volunteers. I'll continue to reach out to people who run various TM instances to see if they work better. But I think we can go ahead and close this issue and create new ones if something comes up.
